### ISSUE TITLE
MIBS requirement

### ISSUE THREAD

**Issue by wouldsmina** [vbarahona/wifiarubausers2grafana#1]
Hi,

great job! useful and simple! I just tested it in a new server, some MIBS need to be added : ARUBA-TC, ARUBA-MIB, WLSX-USER-MIB and WLSX-WLAN-MIB. I fetched it from [libreNMS project](https://github.com/librenms/librenms/tree/35414a73c7847b35a5448dda61e71dcf12f52633/mibs/arubaos)...

Thanks for this dashboard!

**Comment by vbarahona** [comment]
Very true!

Now the WLSX-USER-MIB (is the only needed) is already added in the repo and in the config section.

Regards.
