### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by stranksa** [vbarahona/wifiarubausers2grafana#5]
Hi,

I have this script collecting stats from 4 Controllers with around 10k users on them peak concurrent during the day (Large public venue). I'm seeing issues when the number of clients gets higher whuch suggests the script isn't completing within the 5 min window. Is there any way to get it to go faster?

Have done some searches on telegraf and snmp performance but can't see anything useful.

Thanks in advance!

Andy

**Comment by vbarahona** [comment]
Hi Stranksa

Unfortunately, not. SNMP is no the best way to get a huge amount of information and the snmp aruba users table in heavy environments is really big.

As far as I know, the only way to keep you graphs coherency is increasing the query interval. To make it you should:

- modify the telegraf interval from 300s to for example 600s
- modify the "GROUP BY time(5m)" in the Continuous Queries section with the same interval

Test it and see if it works for you.

Regards.

**Comment by stranksa** [comment]
Hi

I assumed as much and amended it earlier this week. It has behaved better since. I was thinking of doing some tuning on which information we do gather so will report back any findings I make.

Regards
Andy

**Comment by vbarahona** [comment]
Hi

Finally, did you made any tuning on which information we do gather. Any improve?

Regards

**Comment by vbarahona** [comment]
Close by inactivity
