### ISSUE TITLE
Aruba IAPs or Controller

### ISSUE THREAD

**Issue by jftuga** [vbarahona/wifiarubausers2grafana#6]
Will this work for a group of about 50 IAPs or does it only work if you are using an Aruba WiFi Controller?

**Comment by vbarahona** [comment]
Hi,

Unfortunately is based in the WLSX-USER MIB used only by Aruba WiFI Controlers. Probably you can build something similar using from AI-AP-MIB the aiClientTable table (.1.3.6.1.4.1.14823.2.3.3.1.2.4)

Regards

**Comment by jftuga** [comment]
Thanks for the follow up. I will investigate the `AI-AP-MIB`.
